config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show] do

  end

  get '/books', to: 'books#index'
  post '/want_to_read', to: 'books#want_to_read'
  post 'current_read', to: 'books#current_read'
  post 'already_read', to: 'books#already_read'
  get '/show_all_books_by_user', to: 'books#show_all_books_by_user'
  get '/want_to_read_books_list', to: 'books#want_to_read_books_list'
  get '/current_read_books_list', to: 'books#current_read_books_list'
  get '/already_read_books_list', to: 'books#already_read_books_list'

  get '/index', to: 'profile#index', as: 'profile'
  get 'profile/follow/:id', to: 'profile#follow', as: 'follow_user'
  delete 'profile/unfollow/:id', to: 'profile#unfollow', as: 'unfollow_friend'

  get '/show', to: 'user_friendship#show', as: 'show_user_friendship'

  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_one_attached :avatar

  after_create :create_profile

  has_many :user_friendships, foreign_key: :user_id, class_name: 'UserFriendship', dependent: :destroy

  # defines a many-to-many relationship between users through the user_friendships join table, allowing you to access a user's friends directly.
  # if i don't have this line, i can't access friends directly from a user, i have to query the user_friendships table to get the friends.
  has_many :friends, through: :user_friendships, source: :friend

  def follow(friend)
    unless self.user_friendships.exists?(friend_id: friend.id)
      self.user_friendships.create(friend_id: friend.id)
    end
  end

  def unfollow(friend)
    self.user_friendships.destroy(friend)
  end

  private

  def create_profile
    Profile.create(user_id: self.id)
  end
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  validates :user_id, :book_id, :status, presence: true

  # queria criar um scope para buscar no banco livros com status want_to_read para um usuario especifico - ver depois como poderia ter feito aqui
  # scope :want_to_read_books, -> { where(status: 'want_to_read') }

  class << self

    def get_books(current_user)
      books = []
      user = current_user

      books_by_user = UserBook.where("user_id = ?", user)

      books_by_user.each do |book|
        books << book.book_id
      end

      books
    end

    def want_to_read_books_list(current_user)
      books_to_read = []
      user = current_user

      to_read_books = UserBook.where(["user_id = ? and status = ?", user, "want_to_read"])

      to_read_books.each do |book|
        books_to_read << book.book_id
      end

      books_to_read
    end

    def get_books_to_list(current_user)
      current_read = []
      user = current_user

      current_read_books = UserBook.where(["user_id = ? and status = ?", user, "current_read"])

      current_read_books.each do |book|
        current_read << book.book_id
      end

      current_read
    end

    def get_read_books_to_list(current_user)
      already_read = []
      user = current_user

      already_read_books = UserBook.where(["user_id = ? and status = ?", user, "already_read"])

      already_read_books.each do |book|
        already_read << book.book_id
      end

      already_read
    end
  end
end

app/models/user_friendship.rb
class UserFriendship < ApplicationRecord
  # the UserFriendship model belongs to a user and a friend (which is also a User).
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: :friend_id

  validates_presence_of :friend_id, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end
end

app/controllers/books_controller.rb
require 'faraday'
require 'devise'

class BooksController < ApplicationController

  def index
    connection = Faraday.new(url: 'http://gutendex.com')
    response = connection.get('/books/')
    body_json = JSON.parse(response.body)

    @books = body_json['results']
    @books_info = []

    @books.each do |book|
      book_info = {
        id: book['id'],
        title: book['title'],
        author: book['authors'],
        image: book['formats']
      }
      @books_info << book_info
    end
  end

  def want_to_read
    book = params[:book_id]
    user_book = UserBook.new(user_id: current_user.id, book_id: book, status: "want_to_read")
    user_book.save!
    flash[:notice] = "Book adding to your want to read list"
    redirect_to root_path
  end

  def current_read
    book = params[:book_id]
    user_book = UserBook.new(user_id: current_user.id, book_id: book, status: "current_read")
    user_book.save!
    flash[:notice] = "Book adding to your current read list"
    redirect_to root_path
  end

  def already_read
    book = params[:book_id]
    user_book = UserBook.new(user_id: current_user.id, book_id: book, status: "already_read")
    user_book.save!
    flash[:notice] = "Book adding to your already read list"
    redirect_to root_path
  end

  def want_to_read_books_list
    books_to_read_by_user = UserBook.want_to_read_books_list(current_user)
    if books_to_read_by_user.present?
      books_list = get_books_for_user(books_to_read_by_user)
      @want_to_read_books = build_book_info(books_list)
    end
  end

  def current_read_books_list
    current_read_by_user = UserBook.get_books_to_list(current_user)
    if current_read_by_user.present?
      books_list = get_books_for_user(current_read_by_user)
      @current_read_books = build_book_info(books_list)
    end
  end

  def already_read_books_list
    already_read_by_user = UserBook.get_read_books_to_list(current_user)
    if already_read_by_user.present?
      books_list = get_books_for_user(already_read_by_user)
      @already_read_books = build_book_info(books_list)
    end
  end

  def show_all_books_by_user
    book_ids = UserBook.get_books(current_user)

    if book_ids.present?
      books_list = get_books_for_user(book_ids)
      @all_books_by_user = build_book_info(books_list)
    end
  end

  def get_books_for_user(book_ids)
    connection = Faraday.new(url: 'https://gutendex.com')

    @books = []

    book_ids.each do |book_id|
      response = connection.get("/books/#{book_id}/")
      if response.status == 200
        parsed_books = JSON.parse(response.body)
        @books << parsed_books
      end
    end
    @books
  end

  def build_book_info(books)
    books_to_list = []

    @books.each do |book|
      book_info = {
        id: book['id'],
        title: book['title'],
        author: book['authors'],
        image: book['formats']
      }
      books_to_list << book_info
    end
    books_to_list
  end
end

app/controllers/profile_controller.rb
require 'devise'

class ProfileController < ApplicationController

  def index
    if params[:email].present?
      @friends = User.where(email: params[:email])
      @following = @friends.select { |friend| current_user.user_friendships.exists?(friend_id: friend.id) }
    else
      @friends = []
      @following = []
    end
  end

  def follow
    friend = Profile.find(params[:id])
    @friend_followed = current_user.follow(friend)
  end

  def unfollow
    friend = UserFriendship.where(friend_id: params[:id], user_id: current_user)
    current_user.unfollow(friend)
  end
end

app/controllers/user_friendship_controller.rb
class UserFriendshipController < ApplicationController
  before_action :authenticate_user!

  def show
    @friends = current_user.friends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/already_read_books_list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My books</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= render partial: 'layouts/sidebar' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

</head>
<body>
<div class="container mt-4">
<h2>Already read books</h2>
<div class="row">
  <% if @already_read_books.present? %>
    <% @already_read_books.each do |book| %>
      <div class="col-md-4 mb-4">
        <div class="card mx-4" style="width: 18rem;">
          <img src="<%= book[:image]["image/jpeg"] %>" class="card-img-top" alt="<%= book[:title] %>" style="width: 50%; height: auto; display: block; margin-left: auto; margin-right: auto;">
          <div class="card-body">
            <h5 class="card-title"><%= book[:title] %></h5>
            <p class="card-text">Author:
              <%= book[:author] && book[:author].any? ? book[:author][0]["name"] : "Unknown" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>You have not any books yet.</p>
  <% end %>
</div>
</div>

</body>
</html>

app/views/books/current_read_books_list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My books</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= render partial: 'layouts/sidebar' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

</head>
<body>
<div class="container mt-4">
<h2>Current read books</h2>
<div class="row">
  <% if @current_read_books.present? %>
    <% @current_read_books.each do |book| %>
      <div class="col-md-4 mb-4">
        <div class="card mx-4" style="width: 18rem;">
          <img src="<%= book[:image]["image/jpeg"] %>" class="card-img-top" alt="<%= book[:title] %>" style="width: 50%; height: auto; display: block; margin-left: auto; margin-right: auto;">
          <div class="card-body">
            <h5 class="card-title"><%= book[:title] %></h5>
            <p class="card-text">Author:
              <%= book[:author] && book[:author].any? ? book[:author][0]["name"] : "Unknown" %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>You have not any books yet.</p>
  <% end %>
</div>
</div>

</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= render partial: 'layouts/sidebar' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

</head>
<body>
  <div class="container mt-4">
    <div class="row">
      <% @books_info.each do |book| %>
        <div class="col-md-4 mb-4">
          <div class="card mx-4" style="width: 18rem;">
            <img src="<%= book[:image]["image/jpeg"] %>" class="card-img-top" alt="<%= book[:title] %>" style="width: 50%; height: auto; display: block; margin-left: auto; margin-right: auto;">
            <div class="card-body">
              <h5 class="card-title"><%= book[:title] %></h5>
              <p class="card-text">Author:
                <%= book[:author] && book[:author].any? ? book[:author][0]["name"] : "Unknown" %>
              </p>
              <% if user_signed_in? %>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Want to Read
                  </button>
                  <ul class="dropdown-menu">
                    <li>
                      <%= form_with url: want_to_read_path, method: :post, local: true do %>
                        <%= hidden_field_tag :book_id, book[:id] %>
                        <%= submit_tag 'Want to Read', class: 'dropdown-item' %>
                      <% end %>
                    </li>
                    <li>
                      <%= form_with url: current_read_path, method: :post, local: true do %>
                        <%= hidden_field_tag :book_id, book[:id] %>
                        <%= submit_tag 'Current Read', class: 'dropdown-item' %>
                      <% end %>
                    </li>
                    <li>
                      <%= form_with url: already_read_path, method: :post, local: true do %>
                        <%= hidden_field_tag :book_id, book[:id] %>
                        <%= submit_tag 'Already Read', class: 'dropdown-item' %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</body>
</html>

app/views/books/show_all_books_by_user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My books</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= render partial: 'layouts/sidebar' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

</head>
<body>
<div class="container mt-4">
<h2>My books</h2>
<div class="row">
  <% if @all_books_by_user.present? %>
    <% @all_books_by_user.each do |book| %>
      <div class="col-md-4 mb-4">
        <div class="card mx-4" style="width: 18rem;">
          <img src="<%= book[:image]["image/jpeg"] %>" class="card-img-top" alt="<%= book[:title] %>" style="width: 50%; height: auto; display: block; margin-left: auto; margin-right: auto;">
          <div class="card-body">
            <h5 class="card-title"><%= book[:title] %></h5>
            <p class="card-text">Author: <%= book[:author][0]["name"] %></p>
            <% if user_signed_in? %>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Want to Read
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= form_with url: want_to_read_path, method: :post, local: true do %>
                      <%= hidden_field_tag :book_id, book[:id] %>
                      <%= submit_tag 'Want to Read', class: 'dropdown-item' %>
                    <% end %>
                  </li>
                  <li><button class="dropdown-item" type="button">Currently reading</button></li>
                  <li><button class="dropdown-item" type="button">Read</button></li>
                </ul>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>You have not any books yet.</p>
  <% end %>
</div>
</div>

</body>
</html>

app/views/books/show_my_books.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My books</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= render partial: 'layouts/sidebar' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

</head>
<body>
<div class="container mt-4">
<h2>My books</h2>
<div class="row">
  <% @all_books_by_user.each do |book| %>
    <div class="col-md-4 mb-4">
      <div class="card mx-4" style="width: 18rem;">
        <img src="<%= book[:image]["image/jpeg"] %>" class="card-img-top" alt="<%= book[:title] %>" style="width: 50%; height: auto; display: block; margin-left: auto; margin-right: auto;">
        <div class="card-body">
          <h5 class="card-title"><%= book[:title] %></h5>
          <p class="card-text">Author: <%= book[:author][0]["name"] %></p>
          <% if user_signed_in? %>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Want to Read
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= form_with url: want_to_read_path, method: :post, local: true do %>
                    <%= hidden_field_tag :book_id, book[:id] %>
                    <%= submit_tag 'Want to Read', class: 'dropdown-item' %>
                  <% end %>
                </li>
                <li><button class="dropdown-item" type="button">Currently reading</button></li>
                <li><button class="dropdown-item" type="button">Read</button></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

</body>
</html>

app/views/books/want_to_read_books_list.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My books</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <%= render partial: 'layouts/sidebar' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

</head>
<body>
<div class="container mt-4">
<h2>Want to read books</h2>
<div class="row">
  <% if @want_to_read_books.present? %>
    <% @want_to_read_books.each do |book| %>
      <div class="col-md-4 mb-4">
        <div class="card mx-4" style="width: 18rem;">
          <img src="<%= book[:image]["image/jpeg"] %>" class="card-img-top" alt="<%= book[:title] %>" style="width: 50%; height: auto; display: block; margin-left: auto; margin-right: auto;">
          <div class="card-body">
            <h5 class="card-title"><%= book[:title] %></h5>
            <p class="card-text">Author:
              <%= book[:author] && book[:author].any? ? book[:author][0]["name"] : "Unknown" %>
            </p>
            <% if user_signed_in? %>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Want to Read
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <%= form_with url: want_to_read_path, method: :post, local: true do %>
                      <%= hidden_field_tag :book_id, book[:id] %>
                      <%= submit_tag 'Want to Read', class: 'dropdown-item' %>
                    <% end %>
                  </li>
                  <li><button class="dropdown-item" type="button">Currently reading</button></li>
                  <li><button class="dropdown-item" type="button">Read</button></li>
                </ul>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>You have not any books yet.</p>
  <% end %>
</div>
</div>

</body>
</html>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">
            <h3>Bookshelf</h3>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <div class="ms-auto d-flex align-items-center">
              <div class="input-group px-2">
                <input type="text" class="form-control" placeholder="Search books" aria-label="Search books">
                <button class="btn btn-outline-secondary" type="button">Search</button>
              </div>
              <% if !user_signed_in? %>
                <%= link_to 'Login', user_session_path,  class: 'btn btn-outline-primary bg-dark-subtle text-dark border-white me-2' %>
                <%= link_to 'Become member', new_user_registration_path, class: 'btn btn-outline-success bg-dark-subtle text-dark border-white' %>
              <% end %>
              <% if user_signed_in? %>
                <nav class="navbar navbar-light bg-light navbar-expand-sm">
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbar-list-4">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <img src="<%= current_user&.avatar.attached? ? url_for(current_user.avatar) : asset_path('default_avatar.png') %>" width="40" height="40" class="rounded-circle">
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <%= link_to 'Profile', profile_path, class: 'dropdown-item' %>
                          <%= link_to 'Friends', profile_path, class: 'dropdown-item' %>
                          <%= link_to 'Log Out', destroy_user_session_path, class: 'dropdown-item' %>
                        </div>
                      </li>
                    </ul>
                  </div>
                </nav>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </div>
    <%= yield %>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshelf</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= render partial: 'layouts/navbar' %>
  </head>
</html>

app/views/user_friendship/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Profile</title>
	<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
	<style>
	.sidebar {
		background-color: #f8f9fa;
		padding: 20px;
		height: 100vh;
	}
		.profile-pic {
			width: 80px;
			height: 80px;
			border-radius: 50%;
			margin-bottom: 15px;
		}
		.username {
			font-size: 1.4rem;
			margin-bottom: 10px;
	}
		.feed { padding: 20px; }

		.feed-item {
			background-color: #ffffff;
			padding: 15px;
			margin-bottom: 15px;
			border-radius: 5px;
			box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
		}
	</style>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 sidebar">
			<div class="text-center">
				<img src="profile-pic.jpg" alt="User Profile Picture" class="profile-pic">
				<h2 class="username">Username</h2>
			</div>
			<nav class="nav flex-column">
				<a class="nav-link active" href="#">Home</a>
				<%= link_to 'Friends', profile_path, class: 'nav-link' %>
				<a class="nav-link" href="#">Favorites</a>
				<a class="nav-link" href="#">Other option</a>
			</nav>
		</div>

		<div class="col-md-10 feed">
			<% if @friends.present? %>
				<div class="row mt-4">
					<div class="col-md-12">
						<h5>Your Friends:</h5>
						<div class="card">
							<div class="card-body">
								<div class="list-group">
									<% @friends.each do |friend| %>
										<div class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
											<div class="d-flex align-items-center">
												<img src="https://via.placeholder.com/50" alt="Profile Picture" class="rounded-circle mr-3">
												<div>
													<h6 class="mb-0"><%= friend.email %></h6>
													<% if friend.username.present? %>
														<small class="text-muted">@<%= friend.username %></small>
													<% end %>
												</div>
											</div>
											<%= button_to 'Unfollow', unfollow_friend_path(friend), method: :delete, class: 'btn btn-secondary btn-sm' %>
										</div>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				</div>
			<% else %>
				<div class="alert alert-info mt-4" role="alert">
					You have no friends yet.
				</div>
			<% end %>
		</div>
	</div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>